admin_index:
    path: /admin
    controller: App\Controller\AdminController::index

admin_generate_fb_long_token:
    path: /admin/generatefbtoken
    controller: App\Controller\AdminController::generateLongLivedFbToken

admin_index_home:
    path: /
    controller: App\Controller\AdminController::login